project:
  type: book

book:
  title: "Política Pública de Proteção das Espécies Ameaçadas"
  author: "Lucas S.B. Jordão"
  date: "23/03/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - pnb.qmd
    - pronabio-conabio.qmd
    - revisao-das-listas.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: lux
      dark: cyborg
    number-sections: false
    css: "style.css"
    include-in-header:
      - text: |
          <script src="nav-arrows.js"></script>

lang: pt


