project:
  type: book
  output-dir: docs

book:
  title: "Política Pública de Tutela e Proteção das Espécies Ameaçadas"
  author: "Lucas S.B. Jordão"
  date: "03/23/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - pnb.qmd
    - pronabio-conabio.qmd
    - portaria-MMA-43.qmd
    - portaria-MMA-443.qmd
    - revisao-das-listas.qmd
    - portaria-299.qmd
    - cncflora.qmd
    - cites.qmd
    - references.qmd
  google-analytics: "G-FKBTWD2L4V"

bibliography: references.bib

format:
  html:
    theme:
      light: brite
      dark: cyborg
    number-sections: false
    number-depth: 4
    toc-depth: 4
    css: "style.css"
    include-in-header:
      - text: |
          <script src="nav-arrows.js"></script>

lang: pt

comments:
  hypothesis: 
    theme: clean
  giscus: 
    repo: lsbjordao/politica-publica-especies-ameacadas
